# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OWMzYjVmMjUyNmU1NDMyYjg0ZGM0YmRjNTM0NWE5YzM3M2ExOTBkNmJmYTNjNzY2ZDM5NjQwNTYwOWZiZjQ3YWZjNzE2NmVjZTNjNGE0YmUzMTk1Yjc0NWMyMTVjMWFkOWY2Y2QwNjM0OTIyYzI2Yjk3MDg3Mzk3ZTZjZGU1OWU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
